export const SHOES_LIST_REQUEST = "SHOES_LIST_REQUEST";
export const SHOES_LIST_SUCCESS = "SHOES_LIST_SUCCESS";
export const SHOES_LIST_FAIL = "SHOES_LIST_FAIL";

export const SHOES_DETAILS_REQUEST = "SHOES_DETAILS_REQUEST";
export const SHOES_DETAILS_SUCCESS = "SHOES_DETAILS_SUCCESS";
export const SHOES_DETAILS_FAIL = "SHOES_DETAILS_FAIL";